### ISSUE TITLE
Versionamento

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/ETv4#1]
Criar arquivo para controle de versão da ET para facilitar a verificação via script.
Por exemplo, em `/usr/local/cmc/` criar um arquivo `version` contendo `ETv4 1.0`.

Nota: iniciar o branch `develop`.

**Comment by brunosoli** [comment]
`ETv4 1.0` não bom. Que tal `ETv4.0` ou `ET-4.0`?

**Comment by Angelin01** [comment]
Sugiro um arquivo com seguinte formato:
```
Estacao-de-Trabalho-CMC
version=[0-9].[0-9]....
```
A partir dai basta separar os campos.

**Comment by brunosoli** [comment]
Ainda sugiro um arquivo `/usr/local/cmc/version` com o conteúdo: `ET-([0-9])(.[0-9])+`
