### ISSUE TITLE
Acesso remoto via Google remote desktop

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/ETv4#100]
## Descrição

Adicionar o google remote desktop a instalação padrão

### A sua melhoria está relacionada com um problema? Por favor descreva

Visando a solução externa a CMC e também notebooks que precisamos dar suporte. A solução encontrada pela equipe de ARQ foi o google remote desktop para acesso remoto a todas as estações/notebooks da CMC;

### Descreva a solução que você gostaria

Por se tratar de ferramenta google, atrelada a solução SERPRO recem dquirida, basta deixar instalado nas estações através do https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

### Descreva as alternativas que você considerou

Já descartadas outras soluções

### Contexto adicional

Precisa deixar instalado no navegador a extensão https://chrome.google.com/webstore/detail/chrome-remote-desktop/inomeogfingihgjfjlpeplalcfajhgai

**Comment by Felipe-T-Oliveira** [comment]
Feito! Testei no ETv4 e no ETv5, funcionou em ambos!

**Comment by brunosoli** [comment]
Cancelamos esta issue? Vide #101

**Comment by Felipe-T-Oliveira** [comment]
> Cancelamos esta issue? Vide #101

Se todos estiverem de acordo la, seria melhor cancelar, nao teria muito sentido manter ela, ah nao ser que em algum futuro fossemos utilizar pra algo, o que duvido muito.
