### ISSUE TITLE
Problemas detectados no uso do branch develop

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/ETv4#117]
Detalhes durante o uso na nova imagem, para registro:

- DTIC  não está no sudores
- Não montou o Terminal na tela pra DTIC (deve ser o Pc com nome errado)
- Vinagre não instalado e acesso ao PC não funciona de outra estação
- Ownlcloud não instalado.

_Originally posted by @tsocher in https://github.com/CMCuritiba/ETv4/issues/99#issuecomment-1011356227_

**Comment by brunosoli** [comment]
- O owncloud não é instalado por padrão, a ideia é abolir o cliente e usar apenas a versão web ou a montagem no navegador de arquivos do cinnamon.
- O vinagre só precisa ser instalado nas máquinas da DTIC, por isso não vai na ETv4.

O resto tem que revisar.
Pode conferir, @sandroizumi?

**Comment by sandroizumi** [comment]
@brunosoli Com relação ao acesso do grupo DTIC, o mesmo não tinha sido informado no arquivo .env na pré-instalação, então os arquivos de configuração do sistema ficarem sem essa informação.

**Comment by tsocher** [comment]
O PC de destino com a img nova não recebeu o pedido de acesso remoto também, quanto ao vinagre.

**Comment by brunosoli** [comment]
O que vimos nos testes é que a notificação não aparecia, mas é configuração do cinnamon. Mas é melhor dar uma conferida.

**Comment by brunosoli** [comment]
Alguma novidade?
O Tarcísio comentou ontem que também há um problema no papel de parede da imagem no desktop.

**Comment by sandroizumi** [comment]
Sim, isso consegui resolver hoje. Problema era que o gerenciador da tela de boas vindas não conseguia definir a resolução adequada, principalmente se tem dois monitores ligados, e ficava com a tela super expandida. Foi só preciso modificar um atributo no arquivo de configuração do Greeter que deu certo.

**Comment by brunosoli** [comment]
@sandroizumi, ficaram acertadas essas questões?

- [ ] Não montou o Terminal na tela pra DTIC (deve ser o Pc com nome errado)
- [ ] O PC de destino com a img nova não recebeu o pedido de acesso remoto também, quanto ao vinagre.

Se ficaram resolvidas, podemos marcar essa issue como resolvida.

**Comment by sandroizumi** [comment]
Resolvido, era problema de nome porque funcionou em duas máquinas ativas com a nova imagem
