### ISSUE TITLE
[MELHORIA] Adicionar mapeamento ownCloud

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/ETv4#118]
## Descrição

Adicionar mapeamento com ownCloud WebDAV (sem utilização de clientes).

### A sua melhoria está relacionada com um problema? Por favor descreva

1. Evitar erro de sincronização
2. Evitar alto consumo de banda
3. Automatizar o mapeamento (evitar que a pasta fique indisponível)

### Descreva a solução que você gostaria

- Automatizar montagem com `pam_mount`

### Descreva as alternativas que você considerou

- `pam_mount`
- fstab (inviável por problemas de segurança e múltiplos logins no mesmo PC)

### Contexto adicional

N/A

**Comment by brunosoli** [comment]
Talvez seja necessário configurar alguma coisa no `pam.d`.

Talvez seja relacionado:
https://serverfault.com/questions/667391/pam-mount-not-working-when-logging-in-from-ssh-or-console
https://stackoverflow.com/questions/59011078/rhel7-pam-mount-trouble-for-ad-accounts
São para RH e CentOS, portanto os caminhos dos arquivos vai ser diferente, mas a lógica é a mesma.

**Comment by Fabiokleis** [comment]
tem este script que alterar algumas coisas do pam, 180-pam-login-offline.sh, vou rodar ele e testar novamente

**Comment by brunosoli** [comment]
Não adianta fazer os testes numa VM fora do domínio, @Fabiokleis. Veja com o @sandroizumi um PC na rede interna onde você possa fazer uns testes. Só cuidado pra não explodir tudo.

**Comment by Fabiokleis** [comment]
beleza! shaushau

**Comment by Fabiokleis** [comment]
Pronto, faltava uma linha no `/etc/pam.d/common-auth` 
que é o `auth    optional        pam_mount.so

**Comment by sandroizumi** [comment]
Blz, deu certo!

**Comment by brunosoli** [comment]
@Fabiokleis, sugiro reativar o branch 118, comitar as alterações e abrir outro PR.

Só lembrando que o script 180 será executado **antes** do 190. De qualquer forma, é importante que a configuração no pam realizada no script 190 **não sobrescreva** as configurações do script 180 e outros.
