### ISSUE TITLE
Erro configuração "mozo"  no mint 19.2

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/ETv4#31]
Erro no script ao utilizar no mint 19.2

**Para Reproduzir**
ao rodar o script principal ocorre erro na configuração do 260-bloqueio-mate.sh

**Comment by brunosoli** [comment]
Vou criar uma milestone como versão 4.2 para o Mint 19.2.

**Comment by joaopedrogalera** [comment]
O Mint 19.2 substitui o Mozo pelo MenuLibre. Fiz um pull request com a alteração.
