### ISSUE TITLE
Não é possível executar o mate-terminal via Ctrl+Alt+Shift+T

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/ETv4#42]
Teclas de atalho `Ctrl+Alt+Shift+T` chamam o comando `gksu mate-terminal` porém o pacote gksu foi descontinuado

Sugestão de solução:
utilizar o pkexec:
`pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY  mate-terminal`

#pkexec sem chamar o DISPLAY não funciona!

**Comment by joaopedrogalera** [comment]
Enviado pull request no branch develop com a correção
