### ISSUE TITLE
Parametrizar configurações sensíveis

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/ETv4#62]
**A sua melhoria está relacionada com um problema ? Por favor descreva.**
Como bons computeiros que somos, sabemos que uma solução genérica é melhor que uma solução que só resolve um caso. Além disso, por segurança, algumas informações não devem ser salvas no controle de versão.

Algumas informações sensíveis ou passíveis de parametrização devem ser informadas para os scripts de configuração da ETv4 através de um arquivo de configuração.

Exemplo de informações:
- Configurações de LDAP
- Usuário(s) padrão
- Senhas
- IPs e/ou servidores de nome, NTP, etc

**Descreva a solução que você gostaria**
Ao executar o script `principal.sh`, ele deve procurar por um arquivo de configurações padrão ou utilizar um passado por parâmetro, por exemplo:
`sudo ./principal.sh --conf arquivo.conf`

**Descreva as alternativas que você considerou**
Sugestões de soluções alternativas são bem vindas.

**Comment by brunosoli** [comment]
Melhor que passar um arquivo por parâmetro pode ser utilizar um `.env` no mesmo diretório que o `principal.sh` e comitar aqui um `.env.example`.

**Comment by brunosoli** [comment]
@lucaslm45, em que pé estamos?

**Comment by lucaslm45** [comment]
@brunosoli criei um arquivo .env usando o .env.example como base, rodei o script principal.sh e funcionou no Linux Mint Mate 19.2
