### ISSUE TITLE
Develop está com erro ao rodar

### ISSUE THREAD

**Issue by cpinheiro26** [CMCuritiba/ETv4#63]
**Descreva o bug**
Ao rodar o Develop, em um determinado ponto a instalação é abortada por 
não encontrar o pacote "drawing" o que não ocorria na versão anterior.

**Para Reproduzir**
Passos para reproduzir o comportamento :
Rode o script

**Comportamento Esperado**
Instalação correta

**Screenshots**
![Captura de Tela 2020-04-07 às 18 14 50](https://user-images.githubusercontent.com/42621363/78813075-df863980-79a2-11ea-9045-602b9669228c.png)

**Desktop (por favor preencha os campos abaixo):**
Mint Tina

**Comment by brunosoli** [comment]
Esse pacote é do Mint 19.3.

**Comment by brunosoli** [comment]
Se a instalação funcionar sem problemas com a versão 19.3, pode fechar esta issue. Basta um teste de instalação simples.
Vou marcar a isseu como **_good first issue_** para alguém assumir.

**Comment by cpinheiro26** [comment]
Issue relacionada a falha de busca de pacotes no repositório atual, nova issue de substituição dos repositórios no script principal resolve este problema.
