### ISSUE TITLE
Repositórios atuais com falha

### ISSUE THREAD

**Issue by cpinheiro26** [CMCuritiba/ETv4#67]
**Descreva o bug**
Repositórios da UFPR utilizados atualmente no script estão com falha em vários pacotes

**Para Reproduzir**
Rodar o script principal.sh 

**Comportamento Esperado**
Instalação correta dos pacotes

**Desktop (por favor preencha os campos abaixo):**
Mint 19.2 e 19.3

**Contexto Adicional**
Substituir os repositórios no script principal.sh pelos do screenshot anexo já testados
UFAL como principal e Globo da base bionic

<img width="598" alt="Captura de Tela 2020-04-15 às 15 03 24" src="https://user-images.githubusercontent.com/42621363/79602951-ce83a980-80c1-11ea-9197-a970ed567cdd.png">

**Comment by brunosoli** [comment]
Para a base ubuntu, substituí o `ubuntu.c3sl.ufpr.br` por `br.archive.ubuntu.com`.
Eu preferiria colocar algum mirror mais genérico para o Mint. Alguma sugestão?

**Comment by diemello** [comment]
testado em imagem padrão 19.2
