### ISSUE TITLE
Atualizar repositório do Owcloud

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/ETv4#82]
**Descreva o bug**
As ET atuais estão com problemas para atualizar/instalar/desinstalar pacotes via apt.

**Para Reproduzir**
Passos para reproduzir o comportamento :
1. Vá até o terminal
2. Rode `apt upgrade`
3. Veja o erro

**Comportamento Esperado**
Que os pacotes sejam manuseados rodem normalmente

**Screenshots**
![image](https://user-images.githubusercontent.com/18293096/80741835-b879de00-8af0-11ea-929d-46daf099240e.png)

**Desktop (por favor preencha os campos abaixo):**
 - OS: Linux Mint
 - Version 19.2

**Contexto Adicional**
**Sugestão de solução:** 
1. Desinstalar o `owncloud-client` e dependencias (verificar o que pede)
2. Atualizar o repo vide [este script](https://github.com/CMCuritiba/ETv4/blob/develop/scripts/030-instala-programas.sh#L12)
3. Instalar `owncloud-client owncloud-client-caja` e dependencias
4. Atualizar a ET

**Comment by sandroizumi** [comment]
Não é possível desinstalar o owncloud-client, mas ao rodar o script, o repositório do owncloud é atualizado e os problemas de atualização e dependências da ET não acontecem mais

**Comment by diemello** [comment]
> Não é possível desinstalar o owncloud-client, mas ao rodar o script, o repositório do owncloud é atualizado e os problemas de atualização e dependências da ET não acontecem mais

qual script vc rodou?

**Comment by sandroizumi** [comment]
Este [script](https://github.com/CMCuritiba/ETv4/blob/develop/scripts/030-instala-programas.sh#L12)
