### ISSUE TITLE
Configurar ownCloud no Contas Online do Cinnamon

### ISSUE THREAD

**Issue by lucaslm45** [CMCuritiba/ETv4#96]
**A sua melhoria está relacionada com um problema ? Por favor descreva.**
No Cinnamon é possível configurar o OwnCloud no Contas Online.

**Descreva a solução que você gostaria**
Deixar o OwnCloud configurado no Contas Online e o usuário digitar apenas a senha da nuvem para acessar.

**Descreva as alternativas que você considerou**
Manter a configuração que era feita no Mate caso não seja possível configurar.

**Contexto adicional**
Nenhum.

**Comment by brunosoli** [comment]
Resolved in #118.
